# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "609b33a1d729587001b458bdc2aeb4e7"
name = "product-comparison-connor"
handle = "product-comparison-connor"
application_url = "https://arrangement-locale-lately-wallpaper.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://arrangement-locale-lately-wallpaper.trycloudflare.com/auth/callback",
  "https://arrangement-locale-lately-wallpaper.trycloudflare.com/auth/shopify/callback",
  "https://arrangement-locale-lately-wallpaper.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
