# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b831b7881e5be1ce54c4f1a11c5af6ef"
name = "product-comparison"
handle = "product-comparison-13"
application_url = "https://logistics-guides-ur-late.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://logistics-guides-ur-late.trycloudflare.com/auth/callback",
  "https://logistics-guides-ur-late.trycloudflare.com/auth/shopify/callback",
  "https://logistics-guides-ur-late.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
