# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92e5966503baef9a8237c021f369ade7"
name = "product-comparison"
handle = "product-comparison-13"
application_url = "https://isa-immigration-edmonton-separate.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://isa-immigration-edmonton-separate.trycloudflare.com/auth/callback",
  "https://isa-immigration-edmonton-separate.trycloudflare.com/auth/shopify/callback",
  "https://isa-immigration-edmonton-separate.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
